global:
  postgresql:
    enabled: true
    auth:
      postgresPassword: "admin2k12!!"
      username: "admin"
      password: "password123!!"

  aurora-serverless:
    enabled: false
    clusterName: "tenant1"
    vpc:
      vpcID: "vpc-XXXX"
    aurora:
      minACU: 3
      maxACU: 6
      engine: "aurora-postgresql"
      engineVersion: "13"
      masterUsername: "adminer"
      masterUserPassword: "password"
      dbInstanceClass: "db.serverless"
  
  activemq:
    enabled: true

  mcrouter:
    statefulset:
      replicas: 2

