postgresql:
  enabled: true
  auth:
    postgresPassword: "admin2k12!!"
    username: "admin"
    password: "password123!!"
  fullnameOverride: "postgres"
  nameOverride: "postgres"

activemq:
  enabled: true

mcrouter:
  controller: "statefulset"
  statefulset:
    replicas: 1

drupal:
  replicaCount: 1
  ingress:
    host: tenant1.ctrld.dev
    tls:
      enabled: true
