global:
  postgresql:
    enabled: true
    auth:
      postgresPassword: "admin2k12!!"
      username: "admin"
      password: "password123!!"

  activemq:
    enabled: true

  mcrouter:
    statefulset:
      replicas: 2

