apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fdr
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/maxc0d3r/argocd-workloads.git
      revision: HEAD
      directories:
      - path: apps/tenants/*
  template:
    metadata:
      name: '{{path[2]}}'
    spec:
      project: "fdr"
      source:
        repoURL: https://github.com/maxc0d3r/argocd-workloads.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
